#!/bin/bash


echo "PyTrack - Other Software Installation"
echo "====================================="

pushd /home/pi

echo -e "\n\nInstalling SSDV"
echo        "==============="

git clone https://github.com/fsphil/ssdv.git
cd ssdv
sudo make install
cd ..

echo -e "\n\nInstalling PiGPIO"
echo        "================="

wget -N abyz.co.uk/rpi/pigpio/pigpio.zip
unzip -u pigpio.zip
cd PIGPIO
make
sudo make install

popd
